name: Export Issues

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd ./.github/actions/export-issues
          npm install

      - name: Run export issues action
        uses: ./.github/actions/export-issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          output: issues.xlsx

      - name: Upload XLSX artifact
        uses: actions/upload-artifact@v4
        with:
          name: issues
          path: issues.xlsx
